server:
  port: 17002
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp16x49cok67o9i8y.mysql.rds.aliyuncs.com:3306/bhgsdb_test?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: bhgs
    password: Bhgs_2018
appInfo:
  webRoot: "/home/bhtest/upload/"
  webPath: "https://static.bihugs.com/bhtest/"
  filePath: "${appInfo.webRoot}"
logging:
  level:
    org.springframework:
      data: info
      security: info
      jta: info
    com.ljwm: debug
  file: "/home/bhtest/log/provider-server.log"

