swagger2:
  basePackage: "com.ljwm.gecko.provider"
  authorization: "Authorization"
  title: "壁虎个税服务商API"
  description: ""
  version: "V1.0"
jwt:
  route:
    freeRouters: "/enum/*,/location/*,/auth/login"

