swagger2:
  basePackage: "com.ljwm"
  authorization: "Authorization"
  title: "壁虎个税客户服务API"
  description: ""
  version: "V1.0"
jwt:
  route:
    freeRouters: "/vkbYoFL1Jz.txt,/PJDiPsGCHo.txt,/template/*,/auth/login,/auth/loginSys,/registerWX,/registerPC,/sendSMS,/enum/*,/uploadfile,/person/*,/reportData/*,/index/*,/excel/**"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.167:3306/geckodb?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
