spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.212:3306/geckodb?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
appInfo:
  pic: "advertisement"
  servicePic: "serviceType"
  webRoot: "D://upload/"
  webPath: "http://192.168.8.208:7005/gecko/"
  filePath: "${appInfo.webRoot}gecko/"
  neditorEnv: "neditor/dev.ueditor.config.json"
  adminPath: "http://192.168.8.208:7005/gecko/"
