aliyun:
  accessKeyId: LTAIIuCCUYL2ZDeu
  accessKeySecret: A8Fs6bHJ7HPdFDoWoZEZ6zlYjL8fJe
  sms:
    enabled: true
    signName: 壁虎个税
    puller:
      reportListener:
        queueName: Alicom-Queue-1220936721755616-SmsReport
        className: com.ljwm.gecko.base.listener.SmsReportListener
      conf:
        threadQueueSize: 30
