jwt:
  tokenHead: "Gecko "
spring:
  http:
    multipart:
      maxRequestSize: 100Mb
      maxFileSize: 100Mb
appInfo:
  pic: "pic"
  webRoot: "D://upload/"
  webPath: "http://192.168.8.208:6900/gecko/"
  filePath: "${appInfo.webRoot}gecko/"
