jwt:
  tokenHead: "Gecko "
spring:
  http:
    multipart:
      maxRequestSize: 100Mb
      maxFileSize: 100Mb
wx:
  xcx:
    appId: wxdefc6532215f6981
    appSecret: da1df9c302a1dafa17a8b1ffbc72b2d5
#appInfo:
#  pic: "advertisement"
#  webRoot: "D://upload/"
#  webPath: "http://192.168.8.167:7005/gecko/"
#  filePath: "${appInfo.webRoot}gecko/"
#  adminPath: "http://192.168.8.167:7005/gecko/"
